### ISSUE TITLE
Local install to act as a resolver ?

### ISSUE THREAD

**Issue by ghost** [segura2010/GoHole#3]
One really awesome use for this is to install it on your dekstop.
Why ?
Because it blocks Ads no matter where your are.

You just change the DNS proxy in your systems configuration.

I was wondering if your interested in this.
It would mean just doing a little bit of research about how MAC, Desktop, Linux setting are.

**Comment by ghost** [comment]
I just realised you use the Proxy in he other repo . I assume this is correct ?
if so please close this !

**Comment by segura2010** [comment]
I recommend to install it on a Raspberry Pi or another computer/server and configure your computer/device to use the DNS server you set up. 

I think it is easy for the user to change the default DNS server just looking for it on Google :)

**Comment by ghost** [comment]
hey @segura2010 
thanks for the tip. I really need it running locally as a local proxy resolver. a RaspberryPI wont cut it for me as i work remote so much in weird networks.

I think i found another one that works for me:
https://github.com/jedisct1/dnscrypt-proxy

Will close..
